# -*- coding: utf-8 -*-
"""
Created on Sat Dec 29 13:26:04 2018

@author: robin
"""
import os
import pandas as pd
os.chdir('C:/Users/robin/Documents/GitHub/SMC-ABC') # Change path to run it on your computer

from functions_oop import *
 
import numpy as np
#from functions import *

N = 4
alpha = 0.9
e = 0.5
pop_size=700
T=10

actual_data = np.array([30,23,15,10,8,5,4,3,2,1]), np.array([1,1,1,1,1,2,4,13,20,282]) # Data described in the paper end of p8
smc_abc = SMC_ABC(actual_data, N, e, pop_size, T, alpha)
smc_abc.sampler(True)

output = smc_abc.output

phi = np.concatenate(output[0][:,:,0].reshape(-1,1))
tau =  np.concatenate(output[0][:,:,1].reshape(-1,1))
xi =  np.concatenate(output[0][:,:,2].reshape(-1,1))

pd.Series(phi).plot(kind='density')
pd.Series(tau).plot(kind='density')
pd.Series(xi).plot(kind='density')


phi_acceptance = output[1][:,:,0].mean(axis=1)
tau_acceptance = output[1][:,:,1].mean(axis=1)
xi_acceptance = output[1][:,:,2].mean(axis=1)

pd.Series(phi_acceptance).plot()
pd.Series(tau_acceptance).plot()
pd.Series(xi_acceptance).plot()

ess = output[2]
pd.Series(ess).plot()

epsilon = output[3]
pd.Series(epsilon).plot() # Bizarre que ca stabilise à epsilon pile poil...


np.array([np.nan, np.nan, np.nan, np.nan]).sum()

a = {0.5232305615101323: 12.4, 0.5464611230202644: 12.4, 0.5696916845303966: 12.4, 0.5929222460405289: 12.4, 0.616152807550661: 12.4, 0.6393833690607933: 12.4, 0.6626139305709255: 12.4, 0.6858444920810577: 0.3999999999999999, 0.7090750535911899: 0.3999999999999999}

a = np.array([[0.38420814, 0.32970059, 0.28609127],
 [0.56648206, 0.20038857, 0.23312937],
 [0.47320322, 0.2259091,  0.30088768],
 [0.44792133, 0.28565127, 0.2664274 ]])


a[0]
a[[0,0]]
type(a)


thetas_chains = [pd.Series([thetas[i][j] for i in range(6)]) for j in range(3)] # Get the p betas chains generated by the MCMB algorithm 
len(thetas_chains[0][0])

a = compute_prior(3)
a/a.sum(axis=1).reshape(-1,1)